services:
  # production
  # ...

  # development
  development:
    build:
      context: .
      target: development # target as "development" build in Dockerfile
    image: development
    container_name: development
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/react-boilerplate
      - ./node_modules:/usr/react-boilerplate/node_modules

  development-storybook:
    build:
      context: .
      target: development
    image: development-storybook
    container_name: development-storybook
    command: npm run storybook
    ports:
      - 6006:6006
    volumes:
      - .:/usr/react-boilerplate
      - ./node_modules:/usr/react-boilerplate/node_modules

  development-test:
    build:
      context: .
      target: development
    image: development-test
    container_name: development-test
    command: npm run test
    volumes:
      - .:/usr/react-boilerplate
      - ./node_modules:/usr/react-boilerplate/node_modules
